labels = {
    "HH1": "HH Cluster",
    "HH2": "HH Number",
    "LN": "LN",
    "FS4": "FS4",
    "CB3": "Child Age",
    "CB4": "Child School Attendance",
    "CB5A": "Child Highest Edu Lvl",
    "CB5B": "Child Highest Edu Yr",
    "CB7": "Child Current Edu Attendance",
    "CB11": "Child Health Insurance",
    "CL3": "Child Hrs. Worked This Week",
    "CL13": "Child Hrs. Worked Last 7 Days",
    "FCD2A": "Privilege Denial Punishment",
    "FCD2B": "Offense Explained Punishment",
    "FCD2C": "Shaken Punishment",
    "FCD2D": "Raised Voice Punishment",
    "FCD2E": "Redirected Efforts Punishment",
    "FCD2F": "Spanking Punishment",
    "FCD2G": "Enhanced Spanking Punishment",
    "FCD2H": "Name Calling Punishment",
    "FCD2I": "Hit Above Neck Punishment",
    "FCD2J": "Hit Limbs Punishment",
    "FCD2K": "Beaten Punishment",
    "FCD5": "Belief in Physical Punishment",
    "FCF26": "Child Depression",
    "HH6": "HH Location Density",
    "HH7": "HH Region",
    "HL4": "Child Gender",
    "ethnicity": "Child Ethnicity",
    "wscore": "HH Wealth Score",
    "WB4": "Mother Age",
    "WB5": "Mother School Attendance",
    "WB6A": "Mother Highest Edu Lvl",
    "WB6B": "Mother Highest Edu Yr",
    "WB14": "Mother Literacy",
    "DV1A": "DV Justified by Movement",
    "DV1B": "DV Justified by Child Neglect",
    "DV1C": "DV Justified by Arguments",
    "DV1D": "DV Justified by Sex Refusal",
    "DV1E": "DV Justified by Cooking Mistakes",
    "VT1": "Mother Victim Aggravated Theft",
    "VT9": "Mother Victim Other Attack",
    "VT20": "Mother Safe in Neighborhood",
    "VT21": "Mother Safe in Home",
    "VT22A": "Experience Ethnic Discrimination",
    "VT22B": "Experience Gender Discrimination",
    "VT22C": "Experience Sexuality Discrimination",
    "VT22D": "Experience Age Discrimination",
    "VT22E": "Experience Religious Discrimination",
    "VT22F": "Experience Ableist Discrimination",
    "VT22X": "Experience Other Discrimination",
    "MA2": "Husband Age",
    "MA3": "Husband Polygamous",
    "AF10": "Mother Memory Difficulty",
    "AF11": "Mother Self-Care Difficulty",
    "AF12": "Mother Communication Difficulty",
    "TA1": "Mother Tried Tobacco",
    "TA14": "Mother Tried Alcohol",
    "LS1": "Overall Life Satisfaction",
    "LS2": "Ladder Life Satisfaction",
    "LS3": "Life Improved Since Last Year",
    "LS4": "Optimism for Next Year",
    "MSTATUS": "Mother Marital Status",
    "CSURV": "Mother Surviving Children Count",
    "CDEAD": "Mother Dead Children Count",
    "disability": "Mother Disability",
    "CL2": "Child Externally Labors",
    "CL12": "Child HH Labors",
    "HC4": "HH Floor Material",
    "HC5": "HH Roof Material",
    "HC8": "HH Electricity",
    "HC11": "HH Computer or Tablet",
    "HC12": "HH Cell Phone",
    "HC13": "HH Home Internet",
    "HC14": "HH Own or Rent",
    "HC15": "HH Owns Arable Land",
    "HC17": "HH Owns Livestock",
    "HC19": "HH Bank Account",
    "TN1": "HH Mosquito Net(s)",
    "WS1": "HH Drinking Water Source",
    "WS3": "HH DWS Location",
    "WS4": "HH Mins to Collect Water",
    "WS7": "HH Water Sufficiency",
    "WS11": "HH Lavatory Type",
    "WS14": "HH Lavatory Location",
    "WS15": "HH Lavatory Shared Outside HH",
    "HW5": "HH Handwashing Substance"
}